module.exports = {
  // This for the alphabetical autogenerated sidebar
  // autoSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Uncomment this if not using the auto sidebar above
  // Uses the docusaurus/docs directory by default as the root of the docs

  // This is an example of what the manual sidebar should look like
  docs: [
    {
      type: 'doc',
      id: 'getting-started',
      label: 'Getting started',
    },
    {
      type: 'category',
      label: 'Fundamentals',
      link: {
        type: 'generated-index',
        title: 'Fundamentals',
        slug: '/fundamentals',
      },
      collapsible: true,
      collapsed: true,
      items: [
        'fundamentals/defining-your-theme',
        'fundamentals/colors',
        'fundamentals/spacing',
        'fundamentals/accessing-the-theme',
        'fundamentals/variants',
        'fundamentals/breakpoints',
        'fundamentals/responsive-values',
        'fundamentals/overriding-styles',
        {
          type: 'category',
          label: 'Components',
          link: {
            type: 'generated-index',
            title: 'Components',
            slug: 'fundamentals/components',
          },
          collapsible: true,
          collapsed: true,
          items: [
            'fundamentals/components/predefined-components',
            'fundamentals/components/custom-components',
          ],
        },
        {
          type: 'category',
          label: 'Restyle functions',
          link: {
            type: 'generated-index',
            title: 'Restyle Functions',
            description:
              'Restyle functions are the bread and butter of Restyle. They specify how props should be mapped to values in a resulting style object, that can then be passed down to a React Native component. The props support responsive values and can be mapped to values in your theme.',
            slug: 'fundamentals/restyle-functions',
          },
          collapsible: true,
          collapsed: true,
          items: [
            'fundamentals/restyle-functions/predefined-restyle-functions',
            'fundamentals/restyle-functions/custom-restyle-functions',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Guides',
        slug: 'guides',
      },
      collapsible: true,
      collapsed: true,
      items: [
        'guides/dark-mode',
        'guides/shopify-design-system',
        'guides/migrating-to-v2',
      ],
    },
  ],
};
