module.exports = {
  // This for the alphabetical autogenerated sidebar
  // autoSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Uncomment this if not using the auto sidebar above
  // Uses the docusaurus/docs directory by default as the root of the docs

  // Manual sidebar below
  docs: [
    {
      type: 'doc',
      id: 'getting-started',
      label: 'Getting started',
    },
    {
      type: 'category',
      label: 'Fundamentals',
      link: {
        type: 'generated-index',
        title: 'Fundamentals',
        slug: '/fundamentals',
      },
      collapsible: true,
      collapsed: true,
      items: [
        'fundamentals/defining-your-theme',
        'fundamentals/colors',
        'fundamentals/spacing',
        'fundamentals/accessing-the-theme',
        'fundamentals/variants',
        'fundamentals/breakpoints',
        'fundamentals/responsive-values',
        'fundamentals/overriding-styles',
        'fundamentals/restyle-functions',
        {
          type: 'category',
          label: 'Components',
          link: {
            type: 'generated-index',
            title: 'Components',
            slug: 'fundamentals/components',
          },
          collapsible: true,
          collapsed: true,
          items: [
            'fundamentals/components/predefined-components',
            'fundamentals/components/custom-components',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Guides',
        slug: 'guides',
      },
      collapsible: true,
      collapsed: true,
      items: [
        'guides/dark-mode',
        'guides/fixture-app',
        'guides/shopify-design-system',
        'guides/migrating-to-v2',
      ],
    },
  ],
};
