name: documentation

on:
  push:
    branches:
      - master
  pull_request:

env:
  RUBY_VERSION: 3.0.3
  NODE_VERSION: 20.11.0

jobs:
  build-documentation:
    name: 'Build documentation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          cd documentation
          yarn
          yarn build
