name: documentation

on:
  push:
    branches:
      - master
  pull_request:

env:
  RUBY_VERSION: 3.0.3
  NODE_VERSION: 20.11.0

jobs:
  build-documentation:
    name: 'Build documentation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          cd documentation
          yarn
          yarn build
