name: Deploy documentation
on:
  push:
    branches:
      - master

env:
  RUBY_VERSION: 3.0.3
  NODE_VERSION: 20.11.0

jobs:
  release:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: yarn
      - name: Install documentation dependencies and build
        run: |
          cd documentation
          yarn
          yarn build
      - name: Publish documentation
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy:documentation -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
